version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development
- package-ecosystem: pip
  directory: "/test"
  schedule:
    interval: daily
    time: "12:15"
    timezone: "Europe/Berlin"
  open-pull-requests-limit: 10
  target-branch: development
